#define STUB(n, sym) __attribute__((visibility("default"))) void n(void) __asm__(sym); void n(void) {}

#if defined(LIBGUI)
STUB(a1, "_ZN7android21SurfaceComposerClientC1Ev")
STUB(a2, "_ZNK7android21SurfaceComposerClient9initCheckEv")
STUB(a3, "_ZN7android21SurfaceComposerClient13createSurfaceERKNS_7String8EjjijPNS_14SurfaceControlEjj")
STUB(a4, "_ZN7android21SurfaceComposerClient21openGlobalTransactionEv")
STUB(a5, "_ZN7android21SurfaceComposerClient22closeGlobalTransactionEb")
STUB(a6, "_ZN7android14SurfaceControl8setLayerEi")
STUB(a7, "_ZN7android14SurfaceControl11setPositionEff")
STUB(a8, "_ZN7android14SurfaceControl7setSizeEjj")
STUB(a9, "_ZN7android14SurfaceControl8setAlphaEf")
STUB(a10, "_ZN7android14SurfaceControl4showEv")
STUB(a11, "_ZN7android14SurfaceControl4hideEv")
STUB(a12, "_ZN7android14SurfaceControl5clearEv")
STUB(a13, "_ZNK7android14SurfaceControl10getSurfaceEv")
STUB(a14, "_ZN7android14SurfaceControl9setMatrixEffff")
STUB(a15, "_ZN7android21SurfaceComposerClient17getBuiltInDisplayEi")
STUB(a16, "_ZN7android16ScreenshotClientC1Ev")
STUB(a17, "_ZN7android16ScreenshotClientD1Ev")
STUB(a18, "_ZN7android16ScreenshotClient6updateERKNS_2spINS_7IBinderEEENS_4RectEb")
STUB(a19, "_ZNK7android16ScreenshotClient9getPixelsEv")
STUB(a20, "_ZNK7android16ScreenshotClient8getWidthEv")
STUB(a21, "_ZNK7android16ScreenshotClient9getHeightEv")
STUB(a22, "_ZNK7android16ScreenshotClient9getStrideEv")
STUB(a23, "_ZNK7android16ScreenshotClient9getFormatEv")
#elif defined(LIBUTILS)
STUB(b1, "_ZNK7android7RefBase9incStrongEPKv")
STUB(b2, "_ZNK7android7RefBase9decStrongEPKv")
STUB(b3, "_ZN7android7String8C1EPKc")
#elif defined(LIBBINDER)
STUB(c1, "_ZN7android12ProcessState4selfEv")
STUB(c2, "_ZN7android12ProcessState15startThreadPoolEv")
#endif
