version: "2"

run:
  timeout: 5m
  go: "1.26"
formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/ygelfand/LANovo
  exclusions:
    paths:
      - scratch
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (net.Conn).Close
        - (*os.File).Close
        - fmt.Fprintf
        - fmt.Fprintln

  exclusions:
    rules:
      - linters: [errcheck]
        source: "^\\s*defer "

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
