version: 2

project_name: lanovo

git:
  ignore_tags:
    - dev

before:
  hooks:
    - make vet
    - make test
    - make payload
    - make manifest

builds:
  - id: host
    main: ./cmd/lanovo
    binary: lanovo
    env:
      - CGO_ENABLED=0
    tags:
      - payload
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ygelfand/LANovo/internal/layout.Version={{.Version}} -X github.com/ygelfand/LANovo/internal/layout.GitCommit={{.Commit}} -X github.com/ygelfand/LANovo/internal/layout.BuildDate={{.Date}}

archives:
  - formats: ["binary"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

release:
  prerelease: auto
  extra_files:
    - glob: ./bin/lanovod
    - glob: ./bin/manifest.json

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native
