// Command gen converts a numeral set's SVG sources into the Go the device carries.
//
// Dev only, run by hand, never on the device and never imported by it. What it writes is checked
// in, the way the Material icons arrive already converted: the device build must not need this
// program, the SVGs, or anything that reads them.
//
//	go run ./internal/tools/numeral/convert segment
//
// With no arguments it does every directory under svg/.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/ygelfand/libcountertop/pkg/display/mark"
)

const (
	root = "internal/ui/numeral"
	svg  = "svg"
)

// glyphs are the eleven files a set has to have, in the order the Set holds them.
var glyphs = []string{"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "colon"}

func main() {
	sets := os.Args[1:]
	if len(sets) == 0 {
		found, err := os.ReadDir(filepath.Join(root, svg))
		if err != nil {
			log.Fatal(err)
		}
		for _, e := range found {
			if e.IsDir() {
				sets = append(sets, e.Name())
			}
		}
	}

	for _, set := range sets {
		if err := convert(set); err != nil {
			log.Fatalf("%s: %v", set, err)
		}
		fmt.Println("wrote", filepath.Join(root, set+".go"))
	}
}

func convert(set string) error {
	dir := filepath.Join(root, svg, set)

	// The design box is read off the first glyph and every other one is held to it. A set whose
	// digits were drawn in different boxes cannot be laid out by arithmetic, which is the whole
	// reason for having a box.
	var w, h int

	out := new(bytes.Buffer)
	fmt.Fprintf(out, "// Code generated by tools/numeral/convert. DO NOT EDIT.\n//\n")
	fmt.Fprintf(out, "// Regenerate with: go run ./internal/tools/numeral/convert %s\n\n", set)
	name := strings.ToLower(set)

	fmt.Fprintf(out, "package numeral\n\n")
	fmt.Fprintf(out, "import \"github.com/ygelfand/LANovo/internal/ui\"\n\n")

	// Only the data. Nothing here registers the set: what the device offers is decided by hand in
	// sets.go, so generating a set is not the same act as shipping one.
	fmt.Fprintf(out, "var %s = Set{\n", name)
	fmt.Fprintf(out, "\tName: %q,\n", title(set))

	blobs := make([]string, 0, len(glyphs))

	for _, g := range glyphs {
		data, err := os.ReadFile(filepath.Join(dir, g+".svg"))
		if err != nil {
			return err
		}

		gw, gh, err := viewBox(data)
		if err != nil {
			return fmt.Errorf("%s: %w", g, err)
		}
		if w == 0 {
			w, h = gw, gh
		}
		if gw != w || gh != h {
			return fmt.Errorf("%s is drawn in %dx%d, the set is %dx%d", g, gw, gh, w, h)
		}

		icon, err := mark.Shaped(data)
		if err != nil {
			return fmt.Errorf("%s: %w", g, err)
		}
		blobs = append(blobs, literal(icon))
	}

	fmt.Fprintf(out, "\tBoxW: %d,\n\tBoxH: %d,\n\n", w, h)

	fmt.Fprintf(out, "\tDigits: [10]ui.Icon{\n")
	for i := range 10 {
		fmt.Fprintf(out, "\t\t%s,\n", blobs[i])
	}
	fmt.Fprintf(out, "\t},\n\n")
	fmt.Fprintf(out, "\tColon: %s,\n", blobs[10])
	fmt.Fprintf(out, "}\n")

	pretty, err := format.Source(out.Bytes())
	if err != nil {
		return fmt.Errorf("formatting: %w", err)
	}
	return os.WriteFile(filepath.Join(root, set+".go"), pretty, 0o644)
}

// names are the sets whose label is not just their directory capitalized, because they are named
// after something that has its own spelling.
var names = map[string]string{
	"dseg": "DSEG",
}

// title is what the picker shows for a set.
func title(set string) string {
	if name, ok := names[set]; ok {
		return name
	}
	return strings.ToUpper(set[:1]) + set[1:]
}

// viewBox reads the design box off the SVG, which is what the Set records so a face can lay digits
// out without measuring anything.
func viewBox(data []byte) (w, h int, err error) {
	s := string(data)

	at := strings.Index(s, `viewBox="`)
	if at < 0 {
		return 0, 0, fmt.Errorf("no viewBox")
	}
	s = s[at+len(`viewBox="`):]

	end := strings.IndexByte(s, '"')
	if end < 0 {
		return 0, 0, fmt.Errorf("unterminated viewBox")
	}

	var x, y int
	if _, err := fmt.Sscan(s[:end], &x, &y, &w, &h); err != nil {
		return 0, 0, fmt.Errorf("viewBox %q: %w", s[:end], err)
	}
	return w, h, nil
}

// literal is the icon as Go source, as a string conversion rather than a slice of numbers: the
// bytes are opaque and a page of them formatted one per line is a page nobody reads.
func literal(b []byte) string {
	var q strings.Builder
	q.WriteString(`ui.Icon("`)

	for _, c := range b {
		switch {
		case c == '"' || c == '\\':
			q.WriteByte('\\')
			q.WriteByte(c)
		case c >= 0x20 && c < 0x7f:
			q.WriteByte(c)
		default:
			fmt.Fprintf(&q, `\x%02x`, c)
		}
	}

	q.WriteString(`")`)
	return q.String()
}
