package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

const source = "https://api.iconify.design/%s/%s.svg"

const out = "internal/ui/mark/mark.go"

type svg struct {
	ViewBox string `xml:"viewBox,attr"`
	Paths   []struct {
		D      string `xml:"d,attr"`
		Fill   string `xml:"fill,attr"`
		Stroke string `xml:"stroke,attr"`
	} `xml:"path"`

	Circles []struct{} `xml:"circle"`
	Rects   []struct{} `xml:"rect"`
	Lines   []struct{} `xml:"line"`
}

type icon struct {
	name  string
	from  string
	bytes []byte
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: icon Name=set:icon [Name=set:icon ...]")
		os.Exit(2)
	}

	icons := make([]icon, 0, len(os.Args)-1)
	for _, arg := range os.Args[1:] {
		name, from, ok := strings.Cut(arg, "=")
		if !ok {
			fmt.Fprintf(os.Stderr, "%q is not Name=set:icon\n", arg)
			os.Exit(2)
		}

		b, err := fetch(from)
		if err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", from, err)
			os.Exit(1)
		}

		icons = append(icons, icon{name: name, from: from, bytes: b})
		fmt.Printf("%-16s %-28s %d bytes\n", name, from, len(b))
	}

	if err := write(icons); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("wrote", out)

	if at := os.Getenv("ICON_PREVIEW"); at != "" {
		if err := preview(icons, at, 96); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Println("wrote", at)
	}
}

func fetch(from string) ([]byte, error) {
	set, name, ok := strings.Cut(from, ":")
	if !ok {
		return nil, fmt.Errorf("not set:icon")
	}

	client := &http.Client{Timeout: 20 * time.Second}
	resp, err := client.Get(fmt.Sprintf(source, set, name))
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("the icon service answered %s", resp.Status)
	}

	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return nil, err
	}
	return build(body)
}

func build(doc []byte) ([]byte, error) {
	var g svg
	if err := xml.Unmarshal(doc, &g); err != nil {
		return nil, err
	}
	if _, err := viewBox(g.ViewBox); err != nil {
		return nil, err
	}

	switch {
	case len(g.Circles) > 0, len(g.Rects) > 0, len(g.Lines) > 0:
		return doc, nil
	case len(g.Paths) == 0:
		return nil, fmt.Errorf("has nothing to draw")
	}

	fills := map[string]bool{}
	for _, p := range g.Paths {
		if p.Stroke != "" && p.Stroke != "none" {
			return doc, nil
		}
		if p.Fill == "none" {
			return doc, nil
		}
		if p.Fill != "" {
			fills[p.Fill] = true
		}
	}
	if len(fills) > 1 {
		return doc, nil
	}

	b, err := viewBox(g.ViewBox)
	if err != nil {
		return nil, err
	}

	enc := start()
	for _, p := range g.Paths {
		if err := convert(enc, b, p.D); err != nil {
			return nil, err
		}
		enc.ClosePathEndPath()
	}
	return enc.Bytes()
}

var vgMagic = []byte{0x89, 'I', 'V', 'G'}

func backquotable(doc []byte) string {
	return strings.TrimSpace(strings.ReplaceAll(string(doc), "`", "'"))
}

func viewBox(s string) (box, error) {
	f := strings.FieldsFunc(s, func(r rune) bool { return r == ' ' || r == ',' })
	if len(f) != 4 {
		return box{}, fmt.Errorf("a viewBox of %q", s)
	}

	var v [4]float32
	for i, part := range f {
		n, err := strconv.ParseFloat(part, 32)
		if err != nil {
			return box{}, fmt.Errorf("a viewBox of %q", s)
		}
		v[i] = float32(n)
	}

	if v[2] <= 0 || v[3] <= 0 {
		return box{}, fmt.Errorf("a viewBox with no area")
	}
	return box{x: v[0], y: v[1], w: v[2], h: v[3]}, nil
}

func write(icons []icon) error {
	var b strings.Builder

	b.WriteString("// Code generated by internal/tools/icon. DO NOT EDIT.\n\n")
	b.WriteString("// Package mark holds the icons that are not in the library shiny ships.\n")
	b.WriteString("//\n")
	b.WriteString(
		"// Each came from Iconify and is kept here so the device build fetches nothing. A filled\n",
	)
	b.WriteString(
		"// monochrome path is IconVG; a stroked, hollow or multicolor one is the svg itself. The\n",
	)
	b.WriteString(
		"// comment on each says where it came from, which is what to pass the tool again to replace it.\n",
	)
	b.WriteString("package mark\n\n")
	b.WriteString("import \"github.com/ygelfand/LANovo/internal/ui\"\n\n")

	for _, i := range icons {
		if !bytes.HasPrefix(i.bytes, vgMagic) {
			fmt.Fprintf(&b, "// %s is %s.\nvar %s = ui.Icon(`%s`)\n\n",
				i.name, i.from, i.name, backquotable(i.bytes))
			continue
		}

		fmt.Fprintf(&b, "// %s is %s.\nvar %s = ui.Icon{", i.name, i.from, i.name)
		for n, v := range i.bytes {
			if n%12 == 0 {
				b.WriteString("\n\t")
			}
			fmt.Fprintf(&b, "%#02x,", v)
			if n%12 != 11 && n != len(i.bytes)-1 {
				b.WriteString(" ")
			}
		}
		b.WriteString("\n}\n\n")
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return err
	}
	return os.WriteFile(out, src, 0o644)
}
