#define STUB(n, sym) __attribute__((visibility("default"))) void n(void) __asm__(sym); void n(void) {}

#if defined(LIBCAMERA_CLIENT)
STUB(a1, "_ZN7android10CameraBaseINS_6CameraENS_12CameraTraitsIS1_EEE16getCameraServiceEv")
STUB(a2, "_ZN7android8hardware15BpCameraService17notifySystemEventEiRKNSt3__16vectorIiNS2_9allocatorIiEEEE")
STUB(a3, "_ZN7android6Camera7connectEiRKNS_8String16Eii")
STUB(a4, "_ZNK7android6Camera13getParametersEv")
STUB(a5, "_ZN7android6Camera13setParametersERKNS_7String8E")
STUB(a6, "_ZN7android6Camera16setPreviewTargetERKNS_2spINS_22IGraphicBufferProducerEEE")
STUB(a7, "_ZN7android6Camera12startPreviewEv")
STUB(a8, "_ZN7android6Camera11stopPreviewEv")
STUB(a9, "_ZN7android10CameraBaseINS_6CameraENS_12CameraTraitsIS1_EEE10disconnectEv")
STUB(a10, "_ZN7android6Camera18setVideoBufferModeEi")
STUB(a11, "_ZN7android6Camera14setVideoTargetERKNS_2spINS_22IGraphicBufferProducerEEE")
STUB(a12, "_ZN7android6Camera14startRecordingEv")
STUB(a13, "_ZN7android6Camera13stopRecordingEv")
#elif defined(LIBGUI)
STUB(b1, "_ZNK7android7Surface25getIGraphicBufferProducerEv")
#elif defined(LIBUTILS)
STUB(c1, "_ZN7android8String16C1EPKc")
STUB(c2, "_ZN7android7String8C1EPKc")
STUB(c3, "_ZNK7android7RefBase9decStrongEPKv")
#elif defined(LIBBINDER)
STUB(d1, "_ZN7android12ProcessState4selfEv")
STUB(d2, "_ZN7android12ProcessState15startThreadPoolEv")
#endif
